### PR TITLE
Adding introduction to numpy/scipy notebook

### PR DESCRIPTION
**Pull request by registerrier**
First version

### CODE REVIEW

**Comment by cdeil** [comment]
@registerrier - Thanks!

Notebook is here: http://nbviewer.jupyter.org/github/registerrier/gammapy-extra/blob/4125b2c909814a47d1c4cbef1e020a42d0becc61/notebooks/using_numpy.ipynb

My comments:

- Use `print()` function, so that the notebook works in Python 3. Try it once in Python 3 to make sure it's OK.
- Another good resource you could point out at the start is: http://www.scipy-lectures.org/
- And try.jupyter.org as a place where people can just try out things without having to install anything.
- The Exercice section at the end should have a heading "Exercise" so that one can link to it.
- For `Poisson_sample_maximum_better`, please change to `poisson_sample_maximum_better` to follow the common Python style and for the docstring, either remove it, or change to the [Numpy docstring standard](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt#sections) style with `Parameter` and `Returns` section to teach people from the start how it's done in Numpy, Scipy, Astropy, Gammapy, ...  . I think the focus here is not yet on teaching people how to write polished code / docs / tests, so just putting a short, informal docstring here would be OK.

**Comment by cdeil** [comment]
@registerrier - OK to merge this Numpy intro notebook? Or did you still want to make edits?

**Comment by registerrier** [comment]
Fine with me.

**Comment by cdeil** [comment]
All examples worked for me with Python 2 and 3.
I've done some minor edits in 984f993 , mostly putting more expressions in their own cells, because I think
```
>>> expression1
output1
>>> expression2
output2
>>> expression3
output3
```
is easier to read than
```
>>> print(expression1)
>>> print(expression2)
>>> print(expression3)
output1
output2
output3
```

**Pull request merged**
