### PR TITLE
Add notebook for cta tutorial

### PR DESCRIPTION
**Pull request by jjlk**
Hi @cdeil, @registerrier , 
Can I have a feed-back on the ~CTA tutorial?
Danke++

### CODE REVIEW

**Comment by cdeil** [comment]
I'll have a look now.

Notebook is here: http://nbviewer.jupyter.org/github/jjlk/gammapy-extra/blob/188cbaa881f536afc2cee9b493e0ccaf49a008b3/notebooks/cta_simulation.ipynb

**Comment by cdeil** [comment]
One thing I'd like to propose is that we try and have a uniform structure to our tutorial notebooks, like in this example:
http://nbviewer.jupyter.org/github/gammapy/gammapy-extra/blob/master/notebooks/first_steps.ipynb

They should always start with an introduction.
You already have that, except: can you please put "Introduction" as heading below the notebook title.
Another thing I usually try to do it to add links to the most-used classes and Functions from the Sphinx docs. I think that could be helpful for users that want to learn more, or also for experienced people to quickly look up the API for the parts of Gammapy covered by the tutorial.

OK if you mention a few classes and link to them at the start?

---

Another thing I would suggest you add at the top is something like this:

http://nbviewer.jupyter.org/github/gammapy/gammapy-extra/blob/master/notebooks/first_steps.ipynb#Setup

For most people (including me), if you don't put 
```
%matplotlib inline
import matplotlib.pyplot as plt
plt.style.use('ggplot')
```
at the top, Figures will appear in pop-up Windows and it'll be a mess.

Also, it'll make your plots a bit more pretty (well, that's a matter of taste, but ggplot or the new MPL 2.0 default is pretty nice IMO)

---

Finally, can you put an Excercises section at the end, please?
http://nbviewer.jupyter.org/github/gammapy/gammapy-extra/blob/master/notebooks/first_steps.ipynb#Exercises

Usually people will struggle to just understand what's there, so at least the first exercise should be really simple, like "vary this parameter and re-execute the notebook, see how the result changes".
After that, if you want, you can also suggest more challenging exercises.

**Comment by cdeil** [comment]
```
plt.figure('PKS 2155-305 spectrum')
spectral_model.plot(energy_range=[10 * u.GeV, 2 *u.TeV])
plt.show()
```
What's the point of the `plt.figure` and `plt.show` calls?
Don't you get the same result if you remove those?

**Comment by cdeil** [comment]
```
abs = dominguez.evaluate(energy=energy, amplitude=1.)
```
`abs` is a Python built-in function that you overwrite.
I.e. if someone executes code later that uses that, they will be utterly confused.
So usually you should try to avoid that if possible.
Can you rename this variable?

**Comment by cdeil** [comment]
You have this:
```
label = {'label': 'Franceschini 2008'}  # for legend
franceschini.plot(energy_range=energy_range, energy_unit='TeV', ax=ax, **label)
label = {'label': 'Finke 2010'}  # for legend
finke.plot(energy_range=energy_range, energy_unit='TeV', ax=ax, **label)
label = {'label': 'Dominguez 2011'}  # for legend
dominguez.plot(energy_range=energy_range, energy_unit='TeV', ax=ax, **label)
```

Maybe put this instead?
```
opts = dict(energy_range=energy_range, energy_unit='TeV', ax=ax)
franceschini.plot(label='Franceschini 2008', **opts)
finke.plot(label='Finke 2010', **opts)
dominguez.plot(label='Dominguez 2011', **opts)
```

**Comment by cdeil** [comment]
One more minor point: maybe rename "Fermi/LAT catalogue" to "Example spectrum: PKS 2155-304 from 3FGL"?

---

So these were all superficial comments for the notebook.
I would have some comments / suggestions for better API of the classes in Gammapy.

But I would suggest we keep everything as-is for now, since we're both short on time now, before the workshop.

---

One more thing, about the results. Is is possible to access them as an attribute or get them as a dict? That's important if people want to run many simulations from a script.
Currently you only show how to print the results:
```
# print simulation results
print(simu)
```

**Comment by jjlk** [comment]
HI @cdeil, could you have a look?
I didn't add that `plt.style.use('ggplot')` because it looks like too old-school for me.
Cheers

**Comment by cdeil** [comment]
@jjlk - Would it be OK if just merge now and I try the notebook with Python 2 and 3 from master (and make little edits if I see e.g. typos)?
Or are you still editing it?

--

We don't have a notebook docs built step at the moment, so currently the idea is that all notebooks are stored with the output shown in the repo, so that users can just "read" it online. We might change this in the future, and just have a version as you put it in the repo, and then a "rendered" version with output generated as part of the docs build.

I'll re-execute the notebook anyways, so I could just do this change in `master` now.

**Comment by jjlk** [comment]
HI @cdeil , 

You can merge it, thanks!

**Comment by cdeil** [comment]
Thanks!
I'll try it out now ...

**Comment by cdeil** [comment]
The notebook works for me on Python 3.

I've done some minor edits in e195e39

* Commit the output. The incorrect EDISP plotting and double plotting are known issues that we hope to fix ASAP. For now we have those in most notebooks.
* Put `import warnings; warnings.filterwarnings('ignore')` at the top, to get rid of the annoying warnings I get from matplotilb plotting and table printing
* Print subset of results table at the end
* I move the `ebl_model_name='franceschini'` to where it's used. Before it was pretty far up in the notebook, and then only used once further down. Usually people don't always work through notebooks linearly, and having sections as self-contained as possible helps.
* I've renamed `src` to `source`, for consistency with all other docs examples in Gammapy.

See you tomorrow!

**Comment by cdeil** [comment]
I forgot: rendered notebook is here:
http://nbviewer.jupyter.org/github/gammapy/gammapy-extra/blob/master/notebooks/cta_simulation.ipynb

@jjlk - feel free to make edits any time.

There's also this one: http://nbviewer.jupyter.org/github/gammapy/gammapy-extra/blob/master/notebooks/spectrum_simulation_cta.ipynb

@jjlk - Should we abandon / delete that, or do you plan to improve it in the coming week or two?
The one you have is already pretty long, so maybe having a second one with likelihood fitting isn't so bad?
Up to you!

**Pull request merged**
