### PR TITLE
Astropy intro

### PR DESCRIPTION
**Pull request by registerrier**
fits manipulation is still missing.

### CODE REVIEW

**Comment by cdeil** [comment]
The notebook `notebooks/using_numpy.ipynb` is in this PR, but also in #55 .

Maybe you forgot to create this branch off of `master`?
A simple way to fix would be to just abandon this PR / branch, and start a new one from Master, adding the `astropy_introduction` notebook.
Alternatively, you can use `git rebase -i master` and remove the commit `notebooks/using_numpy.ipynb` here (but be careful to not delete your notebooks)

Rendered notebook is here:
http://nbviewer.jupyter.org/github/registerrier/gammapy-extra/blob/ff8d1bd4e11f77a0304458c47520469f99e9dba4/notebooks/astropy_introduction.ipynb

It looks excellent.

one suggestion: [here](http://nbviewer.jupyter.org/github/registerrier/gammapy-extra/blob/ff8d1bd4e11f77a0304458c47520469f99e9dba4/notebooks/astropy_introduction.ipynb#Reprojections) I would suggest you use the term "coordinate transformations" instead of "reprojection". That's the terminology used in Astropy.

When you load the catalog, do it from `../datasets/catalogs/fermi/gll_psc_v16.fit.gz` in this repo to make it work for people if they are offline.
You can still keep the loading from a URL example, in a commented-out comment below using the bundled version, to show people that this option exists.

**Comment by cdeil** [comment]
Similarly `SkyCoord.from_name("M31")` is making a request to the SESAME web service.
This will fail sometimes for users (e.g. if they are offline) and also be a problem in continuous integration testing.

So please replace this with something like what I did here:
http://nbviewer.jupyter.org/github/gammapy/gammapy-extra/blob/master/notebooks/image_analysis.ipynb#Counts-image
```
source_pos = SkyCoord(83.633083, 22.0145, unit='deg')
# If you have internet access, you could also use this to define the `source_pos`:
# source_pos = SkyCoord.from_name('crab')
```

**Comment by cdeil** [comment]
Suggest to replace:
```
# energy loss rate of an electron of kinetic energy E in magnetic field B
def electron_energy_loss_rate(B, E):
```
with 
```
def electron_energy_loss_rate(B, E):
    """Energy loss rate of an electron of kinetic energy E in magnetic field B."""
```
This has the advantage that it leads to re-usable, documented functions, i.e. after you can do
```
help(electron_energy_loss_rate)
```
or
```
print(electron_energy_loss_rate.__doc__)
```
and have the doc for the function attached to the function. 
A comment before the function doesn't do that.

**Comment by cdeil** [comment]
Suggest to change
```
# First row
table[1]
```
to
```
# Second row (with row index 1)
table[1]
```

**Comment by cdeil** [comment]
```
# Spectral index of the 10 first entries
table[1:10]['Spectral_Index']
```
This is 9 entries. First ten entries is via `table[:10]`

**Comment by cdeil** [comment]
Suggest to rename this variable
```
min_index = table[np.argmin(table['Spectral_Index'])]
```
to `row` or `source`.
I find calling it an index confusing.
(it's a `Row` object)

**Comment by cdeil** [comment]
This can be improved:
```
### The list of object types. 
class_list = ['     ','psr  ','spp  ', 'fsrq ', 'bll  ', 'bin  ']
### The colors used for the plot
color_list = ['k', 'b', 'g', 'y', 'r','c']

### We use enumerate which gives us an iterator and its index in the collection
for i,cl in enumerate(class_list):
    print i, cl
```

- Use print function so that it works on Python 3

- If you stick with this approach of two lists, use the more Pythonic way of
```python
source_classes = ['     ','psr  ','spp  ', 'fsrq ', 'bll  ', 'bin  ']
colors = ['k', 'b', 'g', 'y', 'r','c']

for source_class, color in zip(source_classes, colors):
    ....
```

Personally I have found the "parallel lists" way of doing things to lead to hard to maintain and extend code, and by now, I'm almost always using the "list of dict" approach:
```python
source_classes = [
    dict(name='spam', color='ham'),
    ...
]
for source_class in source_classes:
    ...
```

For this small list with 6 entries it's still possible to read and see which color goes with which source class, but it's even clearer with the list of dict approach IMO (even if a little more verbose). If you don't like the verbosity of "lists of dicts", there's also this option:
```python
source_classes = [
    ('psr', 'b'),
    ...
]
for source_class, color in source_classes:
    ...
```

**Comment by cdeil** [comment]
Can you try and use style `ggplot`?
We use that for most notebooks, and the MPL default pre 2.0 are ugly, no?

**Comment by cdeil** [comment]
> Let's try to find sources inside a rectangular region in the sky.

You then go on to do a circular "cone search", not a rectangular region.

Actually sky rectangle and sky ellipse contains are currently not implemented, and we discussed that they aren't really well-defined and we'd remove them, only leaving contains for the special sky regions where it it well defined (circle and polygon).

This is a potential "gotcha" that probably people will run into, so you could mention it. 
Not sure if it's useful to point out.
Maybe just change the description and fix "rectangle" -> "circle".

**Comment by cdeil** [comment]
I suggest to add a mention / example of the following methods for `Table`, which I use all the time while working with tabular data:

Get an overview what's in a table:
```
table.info()
table.info('stats')
```

Nice display of table content as HTML, with a search field:
```
table.show_in_browser(jsviewer=True)
table.show_in_notebook(jsviewer=True)
```

There is also the `table.to_pandas` and Table.from_pandas` converters:
http://docs.astropy.org/en/stable/table/pandas.html
Pandas isn't used very much by astronomers yet, but more and more, and pandas.DataFrame has many highly efficient and convenient methods that Astropy Table doesn't.
The three reasons Astropy Table exists at all (instead of using pandas.DataFrame in the Astropy core) is outlined at the end of this page:
http://docs.astropy.org/en/stable/table/pandas.html

I suggest a mention of pandas to the tutorial, and to also point out one "trick" needed for it to work: drop array-valued columns before converting to pandas:
```
scalar_colnames = tuple(name for name in table.colnames if len(table[name].shape) <= 1)
data_frame = table[scalar_colnames].to_pandas()
```

If you want to add an example, you could with one line compute the number of objects in each source class by calling a pandas method.

**Comment by cdeil** [comment]
One last suggestion: you could mention the option to send images and tables back and forth with GUI tools like TOPCAT / DS9 / Aladin:
http://docs.astropy.org/en/stable/vo/samp/example_table_image.html

It's not something I'm using, and I'm not suggesting to extend the tutorial notebook in that direction.
But if someone needs it or wants it (for partly interactive analysis via GUI), I think it's good to know that this exists and can be used instead of communicating via files. (I think those SAMP communications actually put temp FITS files in the background, the actual data doesn't go directly over the HTTP connection).

**Comment by cdeil** [comment]
For `Table.read`, the `hdu=<number or name>` option is important to mention.
Many people get stuck if there's more than one table in a FITS file, and they don't know how to access it.

So you could show them how to list the HDUs in the catalog file via
```
from astropy.io import fits
fits.open('filename.fits').info()
```
and then load an HDU by name or int index.

**Comment by cdeil** [comment]
Mention `table.meta`?
It's very common to need to read or write header keys, no?

**Comment by registerrier** [comment]
OK. I mistakenly created the branch inside the previous one...
I am going back to master and do a new one. 
Will this be an issue for the other notebook?

**Comment by cdeil** [comment]
Another thing that people commonly want to do, but don't know how is to store multiple tables in one FITS files. The pattern is to use http://docs.astropy.org/en/stable/io/fits/api/tables.html#table-to-hdu and do this:
```python
from astropy.table import Table
from astropy.io import fits
rows = [
    dict(a=42, b='spam'),
    dict(a=43, b='ham'),
]
table1 = Table(rows=rows)
table2 = Table(rows=rows)
hdu_list = fits.HDUList([
    fits.PrimaryHDU(), # need an empty primary HDU
    fits.table_to_hdu(table1),
    fits.table_to_hdu(table2),
])
hdu_list.writeto('tables.fits')
```

**Comment by cdeil** [comment]
> Will this be an issue for the other notebook?

No, the other branch will not care, the commits and files there will stay as-is.

**Comment by cdeil** [comment]
That's it ... I have no further comments.

I know I have suggested a lot of additions for `Table`, and the notebook is getting long.
But from what I've seen, knowing how to work with tables is key to using Astropy / Gammapy for analysis, or contributing to Gammapy.

The other thing that's missing here is `WCS`. I think it's OK to not introduce it here, but to instead do that in the other notebook where we introduce the `SkyMap` class.

**Comment by cdeil** [comment]
I think this PR was superseded by #57 .
Closing now.

(I'll try the notebook in master now)

**Comment by cdeil** [comment]
I've updated the `astropy_introduction.ipynb` notebook in 4021f9c :

- Fixed one issue with Python 3.
- Added some more text to introduction
- Added a section "setup" with some extra things (show version numbers)
- Added a section on making a table from scratch and writing tables
- Added a section on pandas using `data_frame['CLASS1'].value_counts()` as example

@registerrier - if you don't want to teach these extra things next week (e.g. pandas) that's completely fine of course. But I've had others ask me about making tables and writing tables and why adding rows doesn't work well, so I wanted to add a bit of extra info and examples to the notebook.

Latest notebook is here: http://nbviewer.jupyter.org/github/gammapy/gammapy-extra/blob/master/notebooks/astropy_introduction.ipynb

**Pull request closed without merging**
