### PR TITLE
Add expected output files

### PR DESCRIPTION
**Pull request by OlgaVorokh**
@adonath 

Add expected output files.

### CODE REVIEW

**Comment by OlgaVorokh** [comment]
Expected files are added for image-ts test in [this](https://github.com/gammapy/gammapy/pull/475) PR.

**Comment by adonath** [comment]
Minor comment: could you rename the file from `expected_output_0.000.fits` to something like `ts_0.000.fits` or `expected_ts_0.000.fits`. So just involve the term `ts` somewhere in the name.
You can simply use `git mv oldname newname` for that. Once this is updated to the new PSF values, I will merge it. Thanks!

**Comment by cdeil** [comment]
@adonath - Merge?

**Comment by adonath** [comment]
Just for reference:

Values in the library test:
```
result.ts[99, 99] = 1705.840212274973
result.niter[99, 99] = 6
result.amplitude[99, 99] = 1.0227934338735763e-09 
``` 
And the values in the reference file `expected_ts_0.000.fits`:
```
result.ts[99, 99] = 1714.1155313404549
result.niter[99, 99] = 6
result.amplitude[99, 99] = 1.0242018614278501e-09
``` 
Some differences are expected due to down-/upsamling, but this is definitely close enough. Will merge the PR now...

**Pull request merged**
