### PR TITLE
Pacman

### PR DESCRIPTION
**Pull request by JouvinLea**
I add the plot in the check/pacman directory

### CODE REVIEW

**Comment by cdeil** [comment]
@JouvinLea - What about the `datasets/hess-crab4-hd-hap-prod2/run023400-023599/run023523/hess_events_023523.fits.gz` and other event list files? Is that HESS data?
If yes, please delete this branch and make a new one with just the pacman example.

**Comment by JouvinLea** [comment]
This is the same events files that you simulated but with the Keyword MUONEFF that I added

**Comment by cdeil** [comment]
Ah, OK.
For the pacman image, do you have a Python script to produce it?
(It's always helpful for future debugging to be able to reproduce examples)

**Comment by JouvinLea** [comment]
For the moment no, this is still in my test_models.py file

**Comment by JouvinLea** [comment]
I did a new PR, so we can delete this one and continue the disucussion in the other one

**Pull request closed without merging**
