### PR TITLE
Fermi-LAT data tutorial notebook

### PR DESCRIPTION
**Pull request by adonath**
This PR adds Fermi-LAT data tutorial notebook. Here a rendered preview:
https://nbviewer.jupyter.org/github/adonath/gammapy-extra/blob/fermi_lat_data_notebook/notebooks/data_fermi_lat.ipynb

### CODE REVIEW

**Comment by cdeil** [comment]
@adonath - This is very nice, thank  you!

It works for me (except for the ipywidgets slider, that isn't working for me, but I've never used it before, so it might must be a problem with my install).

I'll make a few suggestions and you decide if you want think it's useful, and if you want to spend the time this week.

---

Concerning content, I think what you have here in this notebook is good, except that it's not clear enough from the tutorial or [FermiLATDataset](http://docs.gammapy.org/en/latest/api/gammapy.datasets.FermiLATDataset.html) docstring if / how that class can be used to make a WCS dataset.

The example only loads a HEALPIX dataset and then pokes around, and at the end reprojects the exposure cube on a WCS-based sky image. But I don't think that this is enough information so that users will see that they can use this to "extract" from this a WCS-based dataset with a counts, exposure and possibly diffuse background cube, such as is the input for the other tutorials using Fermi-LAT data:
* https://github.com/gammapy/gammapy-extra/blob/master/notebooks/fermi_vela_model.ipynb
* https://github.com/gammapy/gammapy-extra/blob/master/notebooks/detect_ts.ipynb

So basically showing an example of how to generate such a WCS-based cube dataset should be given, and it fits best at the end of the notebook you have here?

The key point that the user can select an arbitrary lon / lat / energy grid for the WCS cube, and then make a counts cube from that, and only then compute matching exposure and possibly diffuse background cube images should be made clear.

So I don't know what this means for this notebook, or the other notebooks.

@adonath - Ideally I think you'd just keep going with this in the coming days / weeks and go all the way to working example with Fermi-LAT analysis (e.g. a circular region-based spectral measurement, or a 2d image or cube analysis), cleaning up or removing the old stuff we have (like the `fermi_vela_model.ipynb` notebook.

I think for aperture photometry, one could also work from the HEALPIX images directly, no?
One would region-filter the events, and just create a 1-dim exposure vector and then proceed to a spectral analysis or making flux points with 1-dim vectors, without ever needing a WCS?

---

Now some small comments:

The first link in the notebook is broken. There's the "s" missing at the end of "datasets".
Correct one: http://docs.gammapy.org/en/latest/api/gammapy.datasets.FermiLATDataset.html

This one is also broken: http://docs.gammapy.org/en/latest/api/gammapy.cube.SkyCubeHPX.html
because `healpix.py` is not listed in `gammapy/cube/__init__.py`.
Maybe we should make it public and have it listed in the docs?
(doesn't mean we need to support it forever)

---

Suggest to always put "FITS" and "HEALPIX" in all-caps in the text because they are abbreviations and especially for FITS then there's no confusion with fits as in fitting.

---

Trying to access the diffuse model file gives this error:
https://gist.github.com/cdeil/71fe2bce37f84d1894ae0252495e9039
Note that it's a NameError. I think there might be a missing import for `NoDataAvailableError` missing?

**Comment by cdeil** [comment]
@adonath - I had problems because I didn't have `ipywidgets` installed, and because I didn't have the `FERMI_DIFFUSE` env variable set, in the middle of the notebook.

As mentioned in https://github.com/gammapy/gammapy/issues/903, I think we should make users aware at the start.
Probably the best way to proceed here is that you just add a little bit of extra info at the start of the notebook, merge tomorrow, and the more uniform / time-consuming improvements mentioned in https://github.com/gammapy/gammapy/issues/903 are done later.

**Comment by adonath** [comment]
Thanks @cdeil for the comments! I've added a section "Estimating basic inpute sky images for high level analyses" to the end of the notebook and addressed most of your minor comments.

**Comment by cdeil** [comment]
@adonath - Thank you very much!

So I'll merge this now, and maybe even mention it tomorrow at the Paris workshop.
You could also mention it in the call on Friday or next week, and try to get one more people involved in coding (i.e. 1, 2, 3d likelihood analysis of this dataset, to develop some part), or testing (trying to reproduce one and then many catalog spectra) for the coming weeks.

**Comment by cdeil** [comment]
So I tried this a bit, and ran into one issue with:
```
images_basic[0].smooth(width=2).plot()
```

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-32-d924eff21022> in <module>()
----> 1 images_basic[0].smooth(width=2).plot()

/Users/deil/Library/Python/3.5/lib/python/site-packages/gammapy/image/core.py in smooth(self, kernel, radius, **kwargs)
   1203         if kernel == 'gauss':
   1204             width = radius / 2.
-> 1205             image.data = gaussian_filter(self.data, width, **kwargs)
   1206         elif kernel == 'disk':
   1207             width = 2 * radius + 1

TypeError: gaussian_filter() got an unexpected keyword argument 'width'
```

This looks to me like an unrelated bug in SkyImage.smooth, no?
@adonath - could you fix this please?
(or if you also don't have time, like me, please file a reminder issue and we'll try to get it done next week.)

**Comment by cdeil** [comment]
So I still don't have the FERMI_DIFFUSE variable set up.

But this should work without needing the Fermi diffuse model:
```
images_basic = image_estimator.run(dataset, ['counts', 'exposure'])
```
But it doesn't:
https://gist.github.com/cdeil/fc07df55f482b36e15eed60671b78332

I didn't look at your implementation, but this could / should be improved, so that exposure can be computed without the huge diffuse model file available, no?
Can you restructure the code to work that way?

**Comment by adonath** [comment]
@cdeil The keyword for the kernel size is called `radius` not `width` (see [here](http://docs.gammapy.org/en/latest/api/gammapy.image.SkyImage.html#gammapy.image.SkyImage.smooth)), because of the keyword forwarding (boundary handling etc.) this fails. But I think the behaviour is alright, or do you request any changes?

Yes, you're right in principle this should work:
```
images_basic = image_estimator.run(dataset, ['counts', 'exposure'])
``` 
The reason why it doesn't work is, that the exposure cube is reprojected first to the grid of the background model to calculate the predicted number of counts image and then this image is reprojected
to the grid requested by the user (this saves a lot of computing time, when the user specifies e.g. small pixel sizes). I'll think about how to handle this better. Maybe we can store the WCS of the galactic diffuse somewhere...or we just export the exposure on the same grid as the galactic diffuse....

**Comment by cdeil** [comment]
As I said, the way I think it should work (and Fermi binned analysis does work e.g.) is that the user defines the counts grid first, and then that is used.

Some users might never care about the Fermi-LAT diffuse model and the background you compute here, it's questionably if that should be in the Fermi dataset class at all or separate.
But it's there now, and it is very common to use it, so let's keep as-is.

But my suggestion is to not go via background for exposure.
Speed is not really a concern here, exposure is computed once and not in the likelihood loop.

**Comment by cdeil** [comment]
About my `radius` / `width` screw-up: OK to leave as-is. There could be a better error message, but it's hard to do in this case and not worth our time at the moment.

**Comment by adonath** [comment]
@cdeil I don't want to waste computing time if an optimization nearly comes for free. I added a simple workaround in https://github.com/gammapy/gammapy/pull/907.

Apart from that I agree that the background estimation should be separated (see TODO comment [here](https://github.com/gammapy/gammapy/blob/master/gammapy/image/basic.py#L158)). I can open an issue for this...

**Comment by cdeil** [comment]
OK. You could add a comment line above the try-except there explaining why it's there.
👍 to merge!

**Pull request merged**
