### PR TITLE
Add section source detection to CTA data analysis notebook

### PR DESCRIPTION
**Pull request by adonath**
This PR adds a source detection section to `cta_data_analysis.ipynb`. This is what it looks like:

https://nbviewer.jupyter.org/github/adonath/gammapy-extra/blob/add_source_detection_to_cta/notebooks/cta_data_analysis.ipynb#Source-detection

@cdeil

### CODE REVIEW

**Comment by cdeil** [comment]
This is great! Thank you.

How long does the TS map computation run.
If it's more then ~ 30 seconds, can you cut the PSF or image more?

Like I said before, I find it weird to treat the PSF like an image.
Especially cutting out the PSF at a target position is weird:
```
images['psf'].cutout(target_position, size= 1.1 * u.deg)
```
Doesn't this invite small usage errors where the user gets an image kernel that's not perfectly centered and then results are shifted?
Wouldn't it be better to treat PSF kernels as their own objects?

In any case, I'm +1 to merge this as-is and then to discuss that point in the future.

The green markers aren't super well visible. Make them fatter or change color or something?
You could also add markers for Sgr A* and G0.9 or show known sources from gamma-cat or something, to make clear that we correctly discovered these two sources.

**Comment by cdeil** [comment]
Here I would suggest to point out that `find_peaks` is from photutils, not Gammapy.
```
Use the functions compute_ts_image and find_peaks to detect point-like sources on the images:
```
You could just have the explicit `photutils.find_peaks` or from whereever it's imported.

**Comment by cdeil** [comment]
This PR seems to have fallen through the cracks.

@adonath - Can you please rebase it (or do a new one copying the content of that section) and take the comments above into account? If no let me know and I'll do it.

**Comment by adonath** [comment]
@cdeil I rebased this PR and addressed the minor comment you had. I'll go ahead and merge now...

**Comment by cdeil** [comment]
Thank you!

**Pull request merged**
