### PR TITLE
Use environment.yml for Dockerfile config

### PR DESCRIPTION
**Pull request by Bultako**
This PR addresses needs defined in #93

### CODE REVIEW

**Comment by Bultako** [comment]
@cdeil - I finally made it to use ``environment.yml`` to build Binder docker container. 

It is actually a different approach to the one we have been used up to now. It seems we cannot create a conda environment inside a docker image in the building process and pretend to use it as kernel of the JupyterHub that Binder provides. Or at least I don't really know how to do it.

This new approach executes a ``binder.py`` python script from the Dockerfile. This script installs the software dependencies parsing ``environment.yml``


If you agree we can merge here, close #93, and create a new branch ``binder`` that will be used for the Binder service.

**Comment by cdeil** [comment]
@Bultako - Thanks for implementing this!

To be honest, it looks pretty hacky, there should be a better way?

So I read over the info at https://mybinder.readthedocs.io/en/latest/index.html

They recommend using only `environment.yml`, and only if needed `postBuild`, and only if that doesn't work, then `Dockerfile`. Is just having an `environment.yml` like [here](https://github.com/binder-examples/conda/blob/master/environment.yml) and option for us? Looking at our Dockerfile now it's not clear to me that we need it at all!?

If we keep the Dockerfile, they say here that `latest` like you put now doesn't work: https://mybinder.readthedocs.io/en/latest/dockerfile.html#preparing-your-dockerfile

**Comment by Bultako** [comment]
> To be honest, it looks pretty hacky

Well, it actually is.

> They recommend using only environment.yml, and only if needed postBuild, and only
>  if that doesn't work, then Dockerfile. Is just having an environment.yml like here and 
> option for us? Looking at our Dockerfile now it's not clear to me that we need it at all!?

We do it with Dockerffile mainly because of this: 
- landing directly into the ``notebooks`` folder hiding the additional ``gammapy-extra`` folder structure
- setting environment variable ``GAMMAPY_EXTRA``used in most of the notebooks
- flexibility to copy in the Dockerfile part of the content of the GitHub repo

> If we keep the Dockerfile, they say here that latest like you put now doesn't work

Yes, you're right. The point is that it actually works pretty well with ``latest`` tag and I don't know how to get the SHA ID from the DockerHub repo, they just throw the name tag.

**Comment by Bultako** [comment]
I have removed the ``latest`` tag and the Binder builds ok.

**Comment by cdeil** [comment]
OK, so it sounds like we need `Dockerfile` or `postBuild`, or maybe strictly `Dockerfile`.

And just to explore one more option: is it possible to avoid the `binder.py`?
It's basically doing what conda should do with `environment.yml` directly, only that we weren't able to figure out how to find the right conda command to install into the current environment instead of making a new one called `gammapy-tutorials`, or to tell Binder to use that conda env as kernel.

I don't have a solution here. For me it's OK to merge as-is. But for the future, we might want to try and ask somewhere to find a solution that is a bit simpler, i.e. doesn't need `binder.py`.

So for now - merge?

**Comment by Bultako** [comment]
Yes, you have exposed the point clearly.
I think a related aspect with this is that ``gamapy-extra`` GitHub repo is more than the standard Gammapy tutorial pack of notebooks. For these kind of mixed-repos I find it reasonable to have a slightly *hacky* Binder implementation. 

I merge now.
Let's see also how things evolve with ``gamapy-extra`` GitHub repo..

**Pull request merged**
