### PR TITLE
Improve some notebooks

### PR DESCRIPTION
**Pull request by JouvinLea**

### CODE REVIEW

**Comment by JouvinLea** [comment]
@cdeil 
Improve for the background model the relativ path at the end, I get a ValueError

**Comment by cdeil** [comment]
@JouvinLea - I don't know what the issue is and don't have time to test.

> I get a ValueError

I don't see this in the notebook. Can you past the code and full traceback here?
Maybe it's because you have `../background` in the index file?
I think we should avoid linking to files that aren't in sub-folders, i.e. never to `..`.
If needed, duplicate the files, or better, directly add the background models in a sub-folder below the index files.

**Comment by JouvinLea** [comment]
Now there is the error!!! It was not for you top look at it now just for us to discuss this afternoon

**Comment by registerrier** [comment]
Works ok for me now.
One should remember that satrapy >1.3 is required

**Pull request merged**
