### PR TITLE
Sherpa source fitting tuto

### PR DESCRIPTION
**Pull request by facero**
first draft

### CODE REVIEW

**Comment by cdeil** [comment]
@facero - Thanks!

Could you please directly replace `image_fitting_with_sherpa.ipynb` with this notebook instead of adding a new one?

You should be able to do it like this:
```
git mv tutorial_fit_sources_sherpa-gammapy-extra.ipynb image_fitting_with_sherpa.ipynb
git commit --amend
```

For the notebook: it would be great if you can add a short section "Introduction" at the start, and "Exercises" at the end where you suggest to the learner to try some things out (e.g. to vary some analysis parameter). This part is not required, if you don't have time, we can just merge as-is and I'll do some edits tomorrow.

**Comment by cdeil** [comment]
One more suggestion: can you add a heading in the markdown cell before In[7] where you compute the TS values and make the table? Then one can link to that part of the notebook.
You might also add one more sentence explaining to people what you do: setting the amlitude to zero for a given component gives you the likelihood for the null hypothesis. This might not be obvious to people ... I remember how confusing I found TS when I started out.

**Comment by facero** [comment]
I can make some edits tomorrow to add the changes you mention. Has the file replacing worked ?

**Comment by cdeil** [comment]
> I can make some edits tomorrow to add the changes you mention.

OK, then I'll leave this PR open for now.

> Has the file replacing worked ?

Yes. You can see the diff here:
https://github.com/gammapy/gammapy-extra/pull/88/files

You just made a new commit second commit:
https://github.com/gammapy/gammapy-extra/pull/88/commits

My suggestion was to "amend" your previous commit.
https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

It doesn't matter much here, you can keep as-is and just do one more commit with the updated notebook tomorrow. Or if you want, you can merge the three commits in one before pushing to Github again, so that this change lands as one clean commit in the repo.
```
edit notebook
git commit -am 'update'
git rebase -i master
# in the editor, keep the first commit as is and mark the other two with "f" for fix-up
git push -f
```

**Comment by facero** [comment]
Wow that’s a lot of github ninja move that I don’t know yet ;-)
Thx for showing me the path !
F.

**Comment by cdeil** [comment]
Basically I'm asking you to squash your commits for the reason meantioned here:
http://astropy.readthedocs.io/en/stable/development/workflow/development_workflow.html#how-to-squash
> Typically we ask to squash when there was a fair amount of trial and error, but the final patch remains quite small, or when files were added and removed

I don't really care about clean version history in the `gammapy-extra` repo, but I have a feeling you might do more git pull requests or reviewing in the coming years, so I thought it's a good time to practice your git-fu! ⚔️ 😸

**Comment by facero** [comment]
So I tried to follow the steps for rebase and push.
In the git log I think I managed to squash commits but I might have break something 
Can you confirm everything is ok ?

The final tutorial is named :
image_fitting_with_sherpa.ipynb

https://github.com/facero/gammapy-extra/tree/sherpa-tuto/notebooks <https://github.com/facero/gammapy-extra/tree/sherpa-tuto/notebooks>

F.

**Comment by cdeil** [comment]
@facero - It's not OK. If you look at the three tabs "discussion" and  "commits" and "files changed" on github, you'll see that now there's merge conflicts, 103 commits and 172 files changed. 

💥 

I think what happened is that you used my command above, which rebased against your local version of the master branch. Instead you should have rebased against the latest "upstream" version of the master branch:
http://astropy.readthedocs.io/en/stable/development/workflow/development_workflow.html#how-to-squash
I'm sorry for suggesting a bad command above.

Suggest to close this PR, and make a new branch / PR.
(or try to rebase against the latest "upstream", i.e. on github in the main repo, master here)

**Pull request closed without merging**
