### PR TITLE
Add last version of the 3FHL catalog (19/07/2017)

### PR DESCRIPTION
**Pull request by jjlk**
Hi @cdeil, @adonath, 
Here is the last version of the 3FHL catalogue (https://fermi.gsfc.nasa.gov/ssc/data/access/lat/3FHL/). Let's Add it to the gammapy-extra repository.

Thanks

### CODE REVIEW

**Comment by cdeil** [comment]
@jjlk - Thanks! I'll remove the old version in `gammapy-extra` and update the filename in the class in Gammapy now directly in master.

**Comment by cdeil** [comment]
Added v18 of extended sources archive: 9a95abadc7029bd124a40f4fcbd1b95d67677480
Remove older 3FHL version gll_psch_v11.fit.gz   6e92f61e40719682a3546d4f4d125bcfbaf373a5

@adonath - Remove v17 extended source archive or should it be used somewhere instead of the latest v18?

**Comment by jjlk** [comment]
@cdeil, 
And we also need to change the default filename use in the `gammapy.catalogs.SourceCatalog3FHL` constructor. Can you edit it directly on the master branch?

**Comment by cdeil** [comment]
> Can you edit it directly on the master branch?
I'm doing it now, as well as a few other changes for Fermi catalog files / code.
I'll go through a PR.

**Comment by adonath** [comment]
@cdeil This depends on whether there are significant changes that change our results :-)  No, I think there is no reason to keep it. I'll compute a model image with the latest version once it's implemented and if I see any changes I don't understand I can still check the git history...

**Comment by cdeil** [comment]
Removed v17 extended templates in 1c9f782 . You should update anyways to the latest catalog for your studies that matches the final 3FHL catalog / paper. Presumably changes will be minor. In the tests, they have changed "Crab pulsar" to "Crab nebula" which makes more sense for that energy range. PR updating Gammapy coming shortly ...

**Pull request merged**
