### PR TITLE
Add ROOT to FITS exporter for point-like IRFs

### PR DESCRIPTION
**Pull request by jjlk**
Hi @cdeil ,
Please find attach the exporter of the point-like IRFs from ROOT to FITS. As an example, you could retrieve the set of private IRF I used (the link is in the code).

Danke ++

### CODE REVIEW

**Comment by jjlk** [comment]
Hi @cdeil ,
What do we do with that? Did you find the time to do what you wanted to do with the exporter?

**Comment by cdeil** [comment]
Just to keep a note of what we discussed on Skype just now:

One concern is whether the format we export to here matches the spec or not: https://github.com/open-gamma-ray-astro/gamma-astro-data-formats/issues/88
Ideally we would fix a good point-like IRF format and have this script export responses in that format now, before giving it to Gernot and CTA starts producing point-like FITS responses.

Other things to improve here:
- add some infos, especially the RAD_MAX info?
- Copy ROOT -> table converter function into this script, because probably we don't want to keep them in Gammapy
- Use astropy.tableTable instead of astropy.io.fits.BinTable
- Add command line interface at the bottom of the script so that it becomes possible to run the script on different files without having to edit it all the time

Then it would be a good time to hand it off to Gernot.

**Comment by jjlk** [comment]
Hi @cdeil, 
Question about organisation. Following @TarekHC 's developements, do you want to use this PR for future developements (using Table, command line interface, etc.) or should we merge this PR and start new ones?

**Comment by cdeil** [comment]
@jjlk - let's use this PR to implement a good converter script.

Note that IRF class write methods will land in Gammapy soon: https://github.com/gammapy/gammapy/pull/1211
We can stick with just using `Table` here, but then still, those are examples how exactly to fill the `Table`, so the code we put here would be very similar.

**Comment by cdeil** [comment]
I've removed `gammapy.utils.root` just now (https://github.com/gammapy/gammapy/pull/81) and I'm closing this PR without merging.

In Gammapy, we were never able to provide / maintain either scripts or actually be the ones to produce FITS IRFs, and I don't think we can / should moving forward. That has to be done by the MC group for now and by the pipeline soon. https://github.com/cta-observatory/ctapipe/issues/308 is still open to discuss this.

@jjlk - I hope that's OK for you? Or do you see an advantage of having IRF converter scripts in gammapy-extra?

**Pull request closed without merging**
