### PR TITLE
Add notebook for background modelling

### PR DESCRIPTION
**Pull request by JouvinLea**
@cdeil 
Add a notebook for background model

### CODE REVIEW

**Comment by cdeil** [comment]
@JouvinLea - Thanks!

Current notebook is here:
http://nbviewer.jupyter.org/github/JouvinLea/gammapy-extra/blob/0b8c8a2962705b6ecbbed0b0b13e247c2b1ed9ba/notebooks/background_model.ipynb

---

Some suggestions:

* [Introduction](http://nbviewer.jupyter.org/github/JouvinLea/gammapy-extra/blob/0b8c8a2962705b6ecbbed0b0b13e247c2b1ed9ba/notebooks/background_model.ipynb#Introduction): 
* Remove the `~` in front of the links. That is something used in ReStructuredText and Sphinx. Unfortunately the docs system in notebooks is different, it used Markdown, which just has `[text](URL)` to make links. Instead put an empty line and a bullet list. It leads to more readable rendering (see example [here](http://nbviewer.jupyter.org/github/gammapy/gammapy-extra/blob/master/notebooks/first_steps.ipynb#Introduction)).
* Please put the imports as [here](http://nbviewer.jupyter.org/github/gammapy/gammapy-extra/blob/master/notebooks/first_steps.ipynb#Setup) at the top, so that for everyone plots will appear "inline" (i.e. in the browser, not as pop-up windows) and look the same, whether they use matplotlib 1 or 2:
```python
%matplotlib inline
import matplotlib.pyplot as plt
plt.style.use('ggplot')
```
If you do this, you can remove the
```
import pylab as plt
plt.ion()
```
part you have further down.
* For the plots, make the cell with `### Plot the acceptance curve` a markdown cell, so that it renders as a heading.
* For the one Figure you have, can you label the axes please?
* Can you add a second Figure that shows a background spectrum at some offset?
* Maybe even a third that shows the EnergyOffsetArray image? I think that class has a `plot` method you can just call?
* At the moment you're using a mix of `Path` and these functions:
```
cwd=os.getcwd()
if os.path.isdir(cwd+"/background"):
    shutil.rmtree(cwd+"/background")
```
I think everything can be done with just `Path` and it'll be simpler.
The documentation for Path is here: https://docs.python.org/3/library/pathlib.html
For example, there's [Path.cwd](https://docs.python.org/3/library/pathlib.html#pathlib.Path.cwd),  [Path.is_dir](https://docs.python.org/3/library/pathlib.html#pathlib.Path.is_dir) and this should be equivalent:
```python
path = Path.cwd() / 'background'
if path.is_dir():
    shutil.rmtree(str(path))
```
(I thought remove operations can also be done via `Path`, but I don't see it now in the docs)
* Please don't use TeVCat, use gamma-cat instead. I want to remove TeVCat ASAP. I didn't try it, but basically it goes like this and should give the same result:
```python
import astropy.units as u
from gammapy.catalog import SourceCatalogGammaCat
cat = SourceCatalogGammaCat()
table = cat.table
table.rename_column('ra', 'RA')
table.rename_column('dec', 'DEC')
radius = table['morph_sigma'].value
radius[np.isnan(radius)] = 0.3
table['Radius'] = radius
```
* Can you end the notebook with some text, not just the code.
Maybe something like
```
Now we've created a background model in the http://gamma-astro-data-formats.readthedocs.io/en/latest/irfs/background/index.html#bkg-2d-format format.
In future tutorials, we will use it as a background model component for source analysis.
```
or really anything that summarises what was done and what might come next, to help the reader a bit.

---

I did not try to run the code.
Maybe after implementing these comments, we just merge and then on Monday all try it from `master` to see if there's any issues.

Something specifically to look out for here is the `remove` commands. We have to be very careful not to overwrite something accidentally on the user's machine. Maybe it would even be better to never remove something, but just make a temp directory at the start (see https://pymotw.com/3/tempfile/#temporary-directories) to be on the safe side?

**Comment by JouvinLea** [comment]
@cdeil 
I change some of your comments!
For the temporary directory we can see later but maybe this is a good idea even if I think the user will run the notebook in a temp directory....
Let see on Monday for this point

**Comment by cdeil** [comment]
Thank you!!!

I'll merge all four notebooks now and try them out tonight or tomorrow, editing things directly in master if I see opportunities to improve something.

**Comment by cdeil** [comment]
I've polished the `background_model.ipynb` notebook a bit in 2a02788 .

The current version is here: http://nbviewer.jupyter.org/github/gammapy/gammapy-extra/blob/master/notebooks/background_model.ipynb

* Simplified path handling
* More sub headings and some more descriptive text
* Sometimes use temp variables to avoid very long lines (e.g. for filenames)

I didn't take the time yet to improve this section:
http://nbviewer.jupyter.org/github/gammapy/gammapy-extra/blob/master/notebooks/background_model.ipynb#Make-new-HDU-index-table-including-background
There should be some more explanations what's going on, or maybe a link to [the IACT data notebook](http://nbviewer.jupyter.org/github/gammapy/gammapy-extra/blob/master/notebooks/data_iact.ipynb) and explanations there how to copy datastores and make / query index tables. I'm not sure yet, so I left as-is for now.

**Pull request merged**
