### PR TITLE
Run black_notebooks.py to run black on all notebooks

### PR DESCRIPTION
**Pull request by cdeil**
This PR runs black_notebooks.py , i.e. runs black on all notebooks (see https://github.com/gammapy/gammapy/issues/1756).

I think this looks good, suggest to merge this now, and then if we're unhappy with the result we can still tweak some code in the future.

@adonath @Bultako - Please have a look and comment.

### CODE REVIEW

**Comment by cdeil** [comment]
Ah, one small issue is that black removes the `;` because it's generally bad coding style in Python.
In the notebooks when making plots, we often have it as the last line at the end of the cell, to suppress the return value of the last statement, which are often Figure or Axes objects to be printed, i.e. only the image to appear.

I don't know what to do here.

Maybe we just accept the text output? Or maybe this behaviour is configurable for notebooks and we can add something at the top of each notebook instead of many `;` throughout the notebook?

**Comment by adonath** [comment]
@cdeil Again I like the results and I think we should do the transition.

The remaining small issue with the `;` after `.plot()` would be acceptable, once we modify our `.plot()` methods to only return the `ax` object. The current status is, that it is not consistent anyway. Some methods return `ax`, while others return a tuple `fig, ax, cbar`. The returned objects are only needed, if users want to modify and improve the plot later. While I think this is a very common thing to do, we could also not return anything and ask the users to create the an `ax` object beforehand and call `.plot(ax=ax)` in case they want to modify the plot (this is actually my preferred solution).

**Comment by cdeil** [comment]
@Bultako - Thanks! I'll re-run black and then merge.

All your points sound great, except this one is a bit controversial:

> I'm thinking on adding an ignore warnings cell at the beginning, before the execution during the docs building process, so we could get rid of red-warnings output cells.

We had discussions on this before and some people felt we shouldn't hide warnings ever. so before you spend time to implement this, maybe leave this for later and we discuss a bit first (e.g. at the gammapy f2f meeting first week of October or one of the weekly calls on Fridays).

@adonath - concerning the plot methods, I don't have an opinion really, you know better.

At least for cases where users can get to the ax and fig via `plt.gca` or `plt.gcf` I'm not even sure returning anything is needed / useful. But I think for some plots like the sky images there's multiple axes e.g. the colorbar and it's not easy to get at those if they aren't returned, so there I'm not sure what to do best. I guess complete uniformity isn't possible given that sometimes multiple axes are involved and sometimes only one?

👍 if you make a separate issue with a proposal if you think we can do better with plot methods.

**Comment by Bultako** [comment]
@cdeil 
> re:  get rid of red-warnings output cells

This is to apply **only** to fixed-HTML formatted tutorials in docs, not notebooks that we can play with. Anyway, let's discuss it later.

**Comment by KwatME** [comment]
Clean .ipynb with https://github.com/KwatME/clean_ipynb?

**Pull request merged**
