### PR TITLE
Added introduction to maps

### PR DESCRIPTION
**Pull request by AtreyeeS**
Hello @cdeil @registerrier @adonath 

I have started making an introduction to maps.
This is still preliminary, and I will clean it up before the coding sprint.
But please take a look if this roughly what should be.

regards,

### CODE REVIEW

**Comment by AtreyeeS** [comment]
Thanks @cdeil for the comments!

I have a version ready from my side for the coding sprint. 
If it looks good to you, you can merge it.

**Comment by cdeil** [comment]
Nice!
I like the advanced `MC_ID` example, i.e. showing something that isn't possible with the current SkyImage / SkyCube.

Maybe move the basic example  "Reading images from fits files" and where you plot to the front?
And put the section where you work with geom and counts and even MapMaker later?

**Comment by cdeil** [comment]
In the introduction I would suggest to add a link to http://docs.gammapy.org/dev/maps/index.html .

E.g. you're not mentioning HEALPix and a few other things at all.
That's OK, keep as is, you have to make a selection.
But do add the link to that docs page for people that want to learn more, maybe even at the start and at the end.

**Comment by AtreyeeS** [comment]
Hi,

I did start off with putting the "Reading images from fits files" in the beginning, but then I felt it is necessary to introduce the map geometry
 (eg: `vela_wmap_rep = vela_wmap.reproject(vela_2fhl.geom)` ). 

Otherwise it is requiring a bit of back and forth...

Have added the links to the docs page.
I also wanted to put in an example of making HEALPix maps, but `import healpy` is failing on my machine. I will try to put in a subsection when I sort this out!

**Pull request merged**
