### PR TITLE
Add cube

### PR DESCRIPTION
**Pull request by JouvinLea**
New PR for just small cubes size

### CODE REVIEW

**Comment by cdeil** [comment]
File size is OK now. Total size of files:
```
$ du -hs test_datasets/cube/
3.0M	test_datasets/cube/
```

@JouvinLea - What are the files in `test_datasets/cube/data`?
Is it a copy of the files in `$GAMMAPY_EXTRA/datasets/hess-crab4-hd-hap-prod2`?

If yes - I don't understand yet why such a copy is needed.
Can we avoid it completely, or at least not commit the duplicated files to the repo?

**Comment by JouvinLea** [comment]
@cdeil 
The thing is that you have to create a new hdu table that point to the background model you just created in background. So maybe if you change the line in the index table to point for the events in ```$GAMMAPY_EXTRA/datasets/hess-crab4-hd-hap-prod2```it will work... but I have to change my script in this case or do it by hand....

**Comment by cdeil** [comment]
Maybe just make the sentence mentioning `GAMMAPY_EXTRA/datasets/hess-crab4-hd-hap-prod2` more clear, saying what you put in the last comment?

Since filesize is small and this is not the final long-term test dataset, I'm OK to duplicate and not spend time with extra scripting now.

**Comment by JouvinLea** [comment]
@cdeil 
I changedthe sentence is it ok now?

**Comment by cdeil** [comment]
Thanks!
Merging this now.

**Pull request merged**
