### PR TITLE
cube for 3D spectral analysis

### PR DESCRIPTION
**Pull request by JouvinLea**
@adonath 
This PR is for the repo in ```https://github.com/gammapy/gammapy-extra/tree/master/test_datasets/```` that contains the cube necessary for the spectral 3D analysis depending if you want to take into account or not the energy resolution.
In this directory there is also the script to produce these cubes

### CODE REVIEW

**Comment by cdeil** [comment]
IMO this is too large to add to gammapy-extra:
```
93M	test_datasets/cube
```

Most of the size is in the two cube files:
```
$ du -h  test_datasets/cube/* 
 44K	test_datasets/cube/background
2.4M	test_datasets/cube/bkg_cube.fits
2.4M	test_datasets/cube/counts_cube.fits
368K	test_datasets/cube/data/run023400-023599/run023523
368K	test_datasets/cube/data/run023400-023599/run023526
364K	test_datasets/cube/data/run023400-023599/run023559
368K	test_datasets/cube/data/run023400-023599/run023592
1.4M	test_datasets/cube/data/run023400-023599
1.4M	test_datasets/cube/data
2.4M	test_datasets/cube/excess_cube.fits
496K	test_datasets/cube/exclusion_mask.fits
2.4M	test_datasets/cube/exposure_cube.fits
 38M	test_datasets/cube/exposure_cube_etrue.fits
 12K	test_datasets/cube/make.py
2.4M	test_datasets/cube/psf_cube.fits
 38M	test_datasets/cube/psf_cube_etrue.fits
 20K	test_datasets/cube/rmf.fits
4.0K	test_datasets/cube/run.lis
2.4M	test_datasets/cube/significance_cube.fits
```

Running `gzip` on them reduces the size, but it's still > 40 MB.

@JouvinLea - Possible to create a smaller (few MB) test dataset without too much work? (e.g. smaller FOV, larger bin size, fewer energy bins)

**Comment by JouvinLea** [comment]
@cdeil 
Are you ok with the README and the total size?

**Comment by cdeil** [comment]
@JouvinLea - This branch still contains the commit 	1e3dfca with the large files.
This means anyone cloning the repo will forever have to download the extra 90 MB, even if you removed / reduced it in subsequent commits.

You have to either make a new branch / pull request, or squash the commits here by doing a rebase against master.

**Comment by JouvinLea** [comment]
@cdeil 
I dis a new PR

**Comment by cdeil** [comment]
Closing this PR. New PR is here: #46

**Pull request closed without merging**
