### PR TITLE
Split spectrum analysis and fitting with sherpa notebooks

### PR DESCRIPTION
**Pull request by registerrier**
OK I split the 2 parts in 2 different notebooks.

I also use high level UI function from sherpa with sh.load_data syntax.

### CODE REVIEW

**Comment by registerrier** [comment]
I merge now?

**Comment by cdeil** [comment]
@registerrier - For me there's some issue with `spectrum_fitting_with_sherpa.ipynb`

The fit fails with messages like:
* WARNING: parameter value p1.ampl is at its minimum boundary 0.0
* the number of parameters must < number of data points

This is with Sherpa version `ciao4.9+1.g1ebebb7`

See here: http://nbviewer.jupyter.org/gist/cdeil/fa6a8cb3b97c7a2c8083c51985081492

@registerrier - Maybe you have an idea what the issue is?
Or @joleroi - maybe you could try that notebook as well, see if it works for you?

**Comment by registerrier** [comment]
The notebook relies on the extraction of OGIP files from spectrum_analysis.ipynb I f there was a problem there it might fail.

**Comment by joleroi** [comment]
You could use the OGIP files in ``gammapy-extra/datasets/hess-crab4_pha`` to make the notebook independent of other notebooks.

**Pull request merged**
