### PR TITLE
Fixed non-linearity in DET (X, Y) binning in CubeBackgroundModel test file.

### PR DESCRIPTION
**Pull request by mapazarr**
@cdeil Please merge, so that I can implement the tests on CubeBackgroundModel from_fits_image/to_fits_image.

### CODE REVIEW

**Comment by cdeil** [comment]
OK, merging this now.

But can you please comment very briefly:
- what was wrong with the old file?
- should we send the fixed version back to Gammalib?

Note that IMO it's important the Gammapy  / Gammalib work with the same input files and we should not do any changes / fixes just in Gammapy and with our example files.

**Comment by mapazarr** [comment]
OK here's the thing:
All bin edges are equally spaced, but at one point there is one bin edge at half the distance between other 2. Similar to this example:

Instead of having:

`bin_edges = [-2,-1, 0, 1, 2]` all bins equally spaced by `1.0`, with 0. in the central position

It was defined as:

`bin_edges =  [-2, -1.333, -0.667, 0.667, 2]` all equally spaced by `1.333`, and instead of the `0` bin, there is an (artificial?) bin edge (in this case `-1.333`) at half the distance (in this case `0.667`) between 2 other valid bin edges.

This was the case for both the `X` and `Y` edges of the test file we took from `GammaLib`, but this is not the case on the files from @mimayer. Those are fine.

As for sending the file back: I'm not sure about this: I just changed the bins, but I left the bg model values untouched, so they are shifted from their original positions. I have no idea if this is correct or wrong, but it doesn't matter for the tests. At some point it would be good to have our own `bg_faker` and produce our own test files. For this purpose, no realistic simulation of the bg is needed. It's enough with simulating a 2D Gaussian for the spatial distribution and a power-law for the energy.

So, can you merge this PR so that I can implement the tests for https://github.com/gammapy/gammapy/pull/299 please?

**Comment by mapazarr** [comment]
@cdeil One thing we can do is ask within the `GammaLib` developers if this behavior is intended or not. If it is, we can forget about the linear `WCS` object in the `~gammapy.background.CubeBackgroundModel` class. Or at least we need to rethink about this. We can further discuss this issue in our Hangout on Wednesday.

**Comment by cdeil** [comment]
Sorry ... forgot to merge this before. It's merged now.

Thanks for the explanation ... yes, some more thought / discussion on DETX/DETY is needed.
And yes, having a faker with Gauss / Powerlaw would be helpful.
When we test interpolation / reprojection, having an option that sets it to zero for one quarter or three quarters of the field of view would also be nice, to test rotation angles when projected into sky maps.

**Comment by mapazarr** [comment]
@cdeil Ok, thanks. I still have one problem: when getting the remote data I get the old file. I use:
```python
filename = '../test_datasets/background/bg_cube_model_test.fits'
filename = datasets.get_path(filename, location='remote')
```
What am I doing wrong? Or does the repo need some time to refresh?
I know the file is good because I downloaded it and manually set the path in the test and it works.

**Comment by mapazarr** [comment]
For the purpose of book keeping. Here is the actual binning:

Old (faulty?) non-linear binning (in x or y):
```
array([-6.016057, -5.443099, -4.870142, -4.297184, -3.724226, -3.437747,
       -3.151268, -2.57831 , -2.005352, -1.432394, -0.859437, -0.286479,
        0.286479,  0.859437,  1.432394,  2.005352,  2.57831 ,  3.151268,
        3.724226,  4.297184,  4.870142,  5.443099,  6.016057])
```
Please notice that it is not centered in 0, even if it is a simmetric interval (start = -end) and an uneven number of elements. Please notice also the element `-3.437747` that does not follow the same spacing that the rest of the elements and is not corresponded by a `3.437747` element. All elements are equidistant from their next neighbours by `0.573`, and `-3.437747` is exactly in the middle between `-3.724226` and `-3.151268`, at `0.287 = 0.573/2` from each one.

What I implemented:
```
array([-6.016057, -5.469143, -4.922228, -4.375314, -3.8284  , -3.281486,
       -2.734571, -2.187657, -1.640743, -1.093829, -0.546914,  0.      ,
        0.546914,  1.093829,  1.640743,  2.187657,  2.734571,  3.281486,
        3.8284  ,  4.375314,  4.922228,  5.469143,  6.016057])
```
Please notice that this is a perfectly linear array, with all elements equidistant from their next neighbours by `0.547`.

**Comment by cdeil** [comment]
@mapazarr – If this example file is causing you trouble, please just write a small function (10 lines or less?) to fake one or use one from Michael (no worries that it's from HESS, Karl is also using some example files from HESS in a public repo https://github.com/cta-observatory/ctapipe-extra/tree/master/datasets).

**Comment by cdeil** [comment]
About the data file, you're probably loading the one from your Astropy cache, which is probably in `~/.astropy`. You can either `rm -r` that or add an option `cache` do `get_path` and pass that along to the Astropy download function:
https://gammapy.readthedocs.org/en/latest/_modules/gammapy/datasets/load.html#get_path
And then call it with `cache=False`.

**Comment by mapazarr** [comment]
Oh, ok, thanks for the tip. I am implementig the `cache` option within this PR: https://github.com/gammapy/gammapy/pull/299.

**Pull request merged**
